package com.example.journalapp.utils;

import com.example.journalapp.ui.note.NoteItem;
import com.example.journalapp.database.entity.NoteItemEntity;

import java.util.ArrayList;
import java.util.List;

/**
 * Utility class for converting between different objects
 */
public class ConversionUtil {


    // Converts a list of NoteItem to a list of NoteItemEntity
    public static List<NoteItemEntity> convertNoteItemsToEntities(List<NoteItem> items, String noteId) {
        List<NoteItemEntity> entities = new ArrayList<>();
        for (NoteItem item : items) {
            entities.add(new NoteItemEntity(
                    null, // ID will be auto-generated by the database
                    noteId,
                    item.getType().ordinal(),
                    item.getContent(),
                    item.getOrderIndex()
            ));
        }
        return entities;
    }

    public static List<NoteItem> convertNoteItemEntitiesToNoteItems(List<NoteItemEntity> noteItemEntities) {
        List<NoteItem> noteItems = new ArrayList<>();
        for (NoteItemEntity entity : noteItemEntities) {
            NoteItem.ItemType itemType = NoteItem.ItemType.values()[entity.getType()]; // Convert int to ItemType
            noteItems.add(new NoteItem(itemType,entity.getItemId(), entity.getContent(), null, entity.getOrderIndex()));
        }
        return noteItems;
    }
}
