package com.example.journalapp.utils;

import android.text.Html;
import android.text.Spannable;
import android.text.SpannableString;
import android.text.SpannableStringBuilder;
import android.text.Spanned;

import com.example.journalapp.ui.note.NoteItem;
import com.example.journalapp.database.entity.NoteItemEntity;

import java.util.ArrayList;
import java.util.List;

/**
 * Utility class for converting between different UI objects
 * Excludes Room Database Conversions
 */
public class ConversionUtil {


    /**
     * Converts a list of NoteItem objects to a list of NoteItemEntity objects
     * Can be used before saving items to a database
     * @param items
     * @param noteId
     * @return
     */
    public static List<NoteItemEntity> convertNoteItemsToEntities(List<NoteItem> items, String noteId) {
        List<NoteItemEntity> entities = new ArrayList<>();
        for (NoteItem item : items) {
            entities.add(new NoteItemEntity(
                    null, // ID will be auto-generated by the database
                    noteId,
                    item.getType().ordinal(),
                    item.getContent(),
                    item.getOrderIndex()
            ));
        }
        return entities;
    }

    /**
     * Converts a list of NoteItemEntity objects ot a list of NoteItem objects
     * Typically used when fetching items from the database to be displayed in UI
     * @param noteItemEntities
     * @return
     */
    public static List<NoteItem> convertNoteItemEntitiesToNoteItems(List<NoteItemEntity> noteItemEntities) {
        List<NoteItem> noteItems = new ArrayList<>();
        for (NoteItemEntity entity : noteItemEntities) {
            // Convert integer type back to ItemType enum
            NoteItem.ItemType itemType = NoteItem.ItemType.values()[entity.getType()];

            // Create a new NoteItem with the data from NoteItemEntity
            noteItems.add(new NoteItem(itemType,entity.getItemId(), entity.getContent(),entity.getOrderIndex()));
        }
        return noteItems;
    }

    /**
     * Convert a Spannable into a String HTML
     * @param spannableBuilder
     * @return a String representing HTML of text
     */
    public static String spannableToHtml(SpannableStringBuilder spannableBuilder){
        return Html.toHtml(spannableBuilder);
    }

    /**
     * Convert HTML String to a Spannable
     * @param html
     * @return a Spannable that can be displayed
     */
    public static SpannableStringBuilder htmlToSpannable(String html){
        Spanned spanned = Html.fromHtml(html);
        return new SpannableStringBuilder(spanned);
    }
}
